services:
  mongodb:
    image: mongo:7.0
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: pagemaster
      MONGO_INITDB_ROOT_PASSWORD: pagemaster123
      MONGO_INITDB_DATABASE: pagemaster
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d

volumes:
  mongodb_data:
